routes:
  - name: users
    paths: ["/api/users"]
    plugins:
      - name: jwt
      - name: rate-limiting
  - name: root 
    paths: ["/*"]
    plugins:
      - name: test
      - name: test2
    backendurl: "httpbin.org"
